#!/bin/bash
#SBATCH --output=logs/%A_%a.output
#SBATCH --partition=gpu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-gpu=8
#SBATCH --mem-per-gpu=32G
#SBATCH --time=12:00:00
#SBATCH --gres=gpu:4
#SBATCH --qos=gpu-8

export RDZV_HOST=$(hostname)
export RDZV_PORT=3681

source /home/mingming.gong/.bashrc
source activate
conda list

cd /home/mingming.gong/ReLA-dev
# bash $1
$1