#!/bin/bash
#SBATCH --output=logs/%A_%a.output
#SBATCH --partition=gpu
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-gpu=8
#SBATCH --mem-per-gpu=32G
#SBATCH --time=12:00:00
#SBATCH --gres=gpu:4
#SBATCH --qos=gpu-8

export RDZV_HOST=$(hostname)
export RDZV_PORT=3681

source /home/mingming.gong/.bashrc
source activate /home/mingming.gong/miniconda3/envs/open_clip

cd /home/mingming.gong/fast-clip
# bash scripts/mask_75.sh
bash $1